### PR TITLE
Add Brazil to organizationRegistrationNumber 

### PR DESCRIPTION
**Pull request by xdmushui**
Brazil also needs to specify this field after testing.

# Thank you for contributing to Partner Center SDK documentation.

## Pull Request information for public contributors: 

1. Use this repo for your changes https://github.com/MicrosoftDocs/partner-center-sdk/

2. We will review your Pull Request as soon as we can. 

## Pull Request information for Microsoft contributors:

1. Use the private repo at https://github.com/MicrosoftDocs/partner-center-sdk-pr/

The public repo is for customer contributions. https://github.com/MicrosoftDocs/partner-center-sdk/

2. Fill out these three items before submitting your pull request to help us track:

   **A. When does this need to go live?** ASAP, or a certain time?
   >

   **B. Provide a link to your Azure DevOps that tracks this task:**
   >

   **C. Who is the primary contact that owns this document? (set ms.author/author metadata)**
   >

3. **Quality control** checks:

- [ ] A. **Acrolinx:** Make sure your Acrolinx score is **above 80 minimum**, but higher is better, and **0 spelling issues**. Acrolinx helps us in English, but also helps our system ensure translation to localized languages is possible.

- [ ] B. **Successful build with no warnings and no suggestions**: Review the build status to make sure **all files are green** (Succeeded).

- [ ] C. **Preview the pages**: Click each **Preview URL** link to view the rendered HTML pages on the review.docs.microsoft.com site to check the formatting and alignment of the page. Scan the page for overall formatting, and look at the parts you edited in detail.

4. **Type #Sign-off to request the merge**:
- Once the pull request is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the Pull Request.  Signing off means the document is ready for review, and can be published at any time.
- If you need to cancel that sign off, type `#hold-off` instead.
- We'll use review in the GitHub site to provide feedback if changes are needed. Once all feedback is addressed, we'll merge the pull request into master branch. The live site publishes twice a day, morning and afternoon.

## For additional assistance:
- Email `PartnerDocs` or mention`@PartnerDocs`
=================

### CODE REVIEW

**Comment by PRMerger8** [comment]
@xdmushui : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by xdmushui** [comment]
For details please see:
https://docs.microsoft.com/en-us/partner-center/announcements/2021-march#15
image

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @dineshvu - Would you review the proposed update to your article? Resolving the merge conflict (that is, incorporating what was added in master in the private repo after the pull request was created) changed the content that's updated here, so I manually added back in the contributor's update (changing **Brazil** to **Brazil(BR)**). Could you assess the update and let us know whether to merge the pull request? Thanks.

**Comment by dineshvu** [comment]
Let me review and get back via comments. Can someone share the ADO for this PR please.
________________________________

**Comment by ktoliver** [comment]
> Let me review and get back via comments. Can someone share the ADO for this PR please.
> […](#)

@dineshvu Thanks. The contributor who opened the pull request appears to be external to Microsoft. This is a community contribution, so I wouldn't expect an Azure DevOps work item to exist, unless one was created by someone at Microsoft in an unrelated effort.

**Comment by dineshvu** [comment]
I approve the change however this is a Microsoft owned documentation so we should ensure the contributors are validated. This change as I understand from my colleague is a planned announcement as part of a product feature launch. @khakiali as FYI

**Comment by v-andreaco** [comment]
Thanks @dineshvu !

Changes to public repos often come from external contributors, which is why MSFT author approval is required to validate.

Merging this now.

**Pull request merged**
