### PR TITLE
Update TOC.yml

### PR DESCRIPTION
**Pull request by jasongroce**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@jasongroce : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@jasongroce : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@jasongroce : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JasonWHowell** [comment]
@jasongroce the dreaded public repo PR 👍

**Pull request closed without merging**
